#!/usr/bin/env zsh

zstyle ':antidote:bundle' file ${ZDOTDIR:-~}/.zplugins
zstyle ':antidote:static' file ${ZDOTDIR:-~}/.zplugins.zsh
zstyle ':antidote:bundle' use-friendly-names 'yes'
zstyle ':antidote:plugin:*' defer-options '-p'

# Set this to whatever you want to use to edit a command
zstyle :zle:edit-command-line editor vim
