#!/usr/bin/env zsh

[[ -r $ZDOTDIR/.zstyles ]] && . $ZDOTDIR/.zstyles

[[ -d ${ZDOTDIR:-~}/.antidote ]] ||
  git clone https://github.com/mattmc3/antidote ${ZDOTDIR:-~}/.antidote

source ${ZDOTDIR:-~}/.antidote/antidote.zsh
antidote load

