gui:
  theme:
    selectedLineBgColor:
      - reverse
    selectedRangeBgColor:
      - reverse
  showFileTree: true
git:
  branchLogCmd: 'git log --graph --all --color=always --decorate --date=relative --oneline'
  paging:
    colorArg: always
    pager: delta --dark --paging=never --theme catppuccin
