git:
  # see ~/.config/git/config
  branchLogCmd: "git l"
  paging:
    colorArg: always
    pager: delta --dark --paging=never
  overrideGpg: true

customCommands:
  - key: "W"
    description: "wip in progess"
    command: 'git commit -m "wip: $(date +"%Y.%m.%d %H:%M:%S")"'
    context: "files"

gui:
  nerdFontsVersion: 3
  showIcons: true
  showFileTree: true
  # https://github.com/catppuccin/lazygit/blob/main/themes/mocha/rosewater.yml
  theme:
    activeBorderColor:
      - '#f5e0dc'
      - bold
    inactiveBorderColor:
      - '#a6adc8'
    optionsTextColor:
      - '#89b4fa'
    selectedLineBgColor:
      - '#313244'
    cherryPickedCommitBgColor:
      - '#45475a'
    cherryPickedCommitFgColor:
      - '#f5e0dc'
    unstagedChangesColor:
      - '#f38ba8'
    defaultFgColor:
      - '#cdd6f4'
    searchingActiveBorderColor:
      - '#f9e2af'
    authorColors:
      '*': '#b4befe'
