# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
version: 2 
transient_prompt:
  foreground: cyan
  background: transparent
  template: "❯ "
final_space: true
blocks:
  - type: prompt
    alignment: left
    segments:
      - type: python
        style: plain
        foreground: "yellow"
        template: " {{ .Full }}"
      - type: git
        foreground: magenta
        # foreground_templates:
        #   - '{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}'
        #   - '{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}'
        #   - '{{ if gt .Ahead 0 }}#B388FF{{ end }}'
        #   - '{{ if gt .Behind 0 }}#B388FF{{ end }}'
        properties:
          branch_max_length: 25
          fetch_stash_count: true
          fetch_status: true
          fetch_upstream_icon: true
        style: plain
        template: >
          {{ .UpstreamIcon }}{{ .HEAD }}{{ if .BranchStatus }}{{ .BranchStatus }}{{ end -}}
          {{ if .Working.Changed }}  {{ .Working.String }}{{ end -}}
          {{ if and (.Working.Changed) (.Staging.Changed) }}|{{ end -}}
          {{ if .Staging.Changed }}  {{ .Staging.String }}{{ end -}}
          {{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end -}}
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: path
        foreground: 'cyan'
        properties:
          style: full
        style: plain
        template:  {{ .Path }}
  - type: prompt
    alignment: right
    segments:
      - type: status
        style: plain
        foreground: 'green'
        foreground_templates:
          - '{{ if gt .Code 0 }}red{{ end }}'
        template: ' x{{ reason .Code }} '
      - type: executiontime
        style: plain
        foreground: 'green'
        foreground_templates:
          - '{{ if gt .Code 0 }}red{{ end }}'
        properties:
          style: austin
        template: ' {{ .FormattedMs }} '
      - type: session
        style: plain
        foreground: darkGray
        template: >
          {{ if .SSHSession }} {{ .UserName}}@{{ .HostName }}{{ end }}
  - type: prompt
    alignment: left
    newline: true
    segments:
      - foreground: 'red'
        style: plain
        template: '!'
        type: root
      - foreground: 'green'
        style: plain
        template: ❯
        type: text

