# yaml-language-server: $schema=https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json
version: 2 
transient_prompt:
  foreground: cyan
  background: transparent
  template: "❯ "
palette:
  rosewater: '#f5e0dc'
  sky: '#89dceb'
final_space: true
shell_integration: true
disable_notice: true
blocks:
  - type: prompt
    alignment: left
    segments:
      # language segments
      - type: python
        style: plain
        foreground: "yellow"
        template: "  {{ .Full }} "
      - type: go
        style: plain
        foreground: "cyan"
        template: " {{ .Full }} "
      - type: rust
        style: plain
        foreground: "red"
        template: " {{ .Full }} "
      - type: node
        style: plain
        foreground: "p:sky"
        template: " {{ .Full }} "
      - type: project
        style: plain
        foreground: "p:rosewater"
        template: >
          {{ if .Error }} {{ .Error }}{{ else -}}
          {{ if .Version }} {{.Version}}{{ end -}}
          {{ if .Name }} {{ .Name }} {{ end }}{{ end -}}
      - type: git
        foreground: magenta
        properties:
          branch_max_length: 25
          fetch_stash_count: true
          fetch_status: true
          fetch_upstream_icon: true
        style: plain
        template: >
          {{ .UpstreamIcon }}{{ .HEAD }}{{ if .BranchStatus }} {{ .BranchStatus }}{{ end -}}
          {{ if .Working.Changed }}  {{ .Working.String }}{{ end -}}
          {{ if .Staging.Changed }}  {{ .Staging.String }}{{ end -}}
          {{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end -}}
  - type: prompt
    alignment: left
    newline: true
    segments:
      - type: path
        style: plain
        foreground: 'cyan'
        properties:
          style: unique
        template:  {{ .Path }}
  - type: prompt
    alignment: right
    segments:
      - type: status
        style: plain
        foreground: 'green'
        foreground_templates:
          - '{{ if gt .Code 0 }}red{{ end }}'
        template: ' x{{ reason .Code }} '
      - type: executiontime
        style: plain
        foreground: 'green'
        foreground_templates:
          - '{{ if gt .Code 0 }}red{{ end }}'
        properties:
          style: austin
        template: ' {{ .FormattedMs }} '
      - type: session
        style: plain
        foreground: darkGray
        template: >
          {{ if .SSHSession }} {{ .HostName }}{{ end }}
  - type: prompt
    alignment: left
    newline: true
    segments:
      - foreground: 'red'
        style: plain
        template: '!'
        type: root
      - foreground: 'green'
        style: plain
        template: ❯
        type: text

