.dotfiles/lib/plugins/base16:
  rereshPeriod: 168h
  type: git-repo
  url: https://github.com/chriskempson/base16-shell.git

.dotfiles/lib/plugins/zsh-defer:
  rereshPeriod: 168h
  type: git-repo
  url: https://github.com/romkatv/zsh-defer.git

.dotfiles/lib/plugins/zsh-syntax-highlighting:
  rereshPeriod: 168h
  type: git-repo
  url: https://github.com/zsh-users/zsh-syntax-highlighting.git

.dotfiles/lib/plugins/fzf-tab:
  rereshPeriod: 168h
  type: git-repo
  url: https://github.com/Aloxaf/fzf-tab.git

.dotfiles/lib/plugins/oh-my-zsh:
  type: archive
  url: https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz
  stripComponents: 2
  refreshPeriod: 168h
  include:
    - "*/lib/{clipboard,completion}.zsh"
    - "*/plugins/{dotenv,extract}/**"

.dotfiles/lib/plugins/fzf:
  type: archive
  # type: git-repo
  url: https://github.com/junegunn/fzf/archive/master.tar.gz
  # url: https://github.com/junegunn/fzf.git
  refreshPeriod: 168h
  stripComponents: 2
  include:
    - "*/shell/*.zsh"
