#!/bin/sh

# enable touch on only laptop monitor
xinput --map-to-output 'ELAN901C:00 04F3:2C29' eDP-1

xss-lock -- ~/bin/lock &

unclutter --timeout 1 &

# set a new random color
~/.config/qtile/.colors/colors.py

SKIP_WM_RESET=1 autorandr -c --default default

