#!/bin/sh

# enable touch on only laptop monitor
# this isn't working for some reason
xinput --map-to-output '18' eDP-1

xss-lock -- ~/bin/lock &

unclutter --timeout 1 &

# set a new random color
~/.config/qtile/colors.py

SKIP_WM_RESET=1 autorandr -c --default default
