[user]
name = "Daylin Morgan"
email = "me@dayl.in"

[signing]
sign-all = true
backend = "gpg"
signingkey = "7AD9DB430EE2B3C1D86BF3243CD66E04B8072F3E"

[git]
private-commits = "description(glob:'wip*') | description(glob:'private:*')"

[ui]
# default-command = "log"
default-command = "l"
pager = "delta"
diff-editor = ":builtin"

[ui.diff]
format = "git"

[aliases]
wip = ["ci", "-m", "wip"]
la = ["log", "-r", "all()"]
bsm = [
  "bookmark", "set", "main", "-r",
  # first non-empty change from current revset
  "latest(::@ & ~empty())"
]
l = ["log", "-T", "log_oneline"]

[revsets]
log = "present(@) | ancestors(immutable_heads().., 3) | present(trunk())"
# default
# log = "present(@) | ancestors(immutable_heads().., 2) | present(trunk())"

[template-aliases]
# adapted from log oneline
log_oneline = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    concat(
      separate(" ",
        format_short_change_id_with_hidden_and_divergent_info(self),
        if(author.email(), author.email().local(), email_placeholder),
        if(description,
          description.first_line(),
          label(if(empty, "empty"), description_placeholder),
        ),
        if(empty, label("empty", "(empty)")),
        bookmarks,
        tags,
        working_copies,
        if(git_head, label("git_head", "git_head()")),
        if(conflict, label("conflict", "conflict")),
      ) ++ "\n",
    ),
  )
)
'''

