name: dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
# Python
  - python
  - pip
  - ipython
  - jupyter
  - yapf
  - snakemake
# Datasci
  - pandas
  - numpy 
  - scipy
  - scikit-learn
  - altair
  - vega_datasets
  - vega
  - vega-cli
  - vega-lite-cli
  - matplotlib
  - seaborn
# WebInteraction
  - requests
  - bs4
  - lxml
  - selenium
  - oauth2client
  - jinja2
# Cli
  - rich
  - bullet-python
# Misc
  - img2pdf
  - bibtexparser
  - pypdf2
  - fuzzywuzzy
  - python-pdfkit
#Go
  - go
#Pip
  - pip:
    - git+https://github.com/DaylinMorgan/alshain
    - ytmusicapi 
