default-icon: 
no-client: "-"
classes:
  "[Running] - Oracle VM VirtualBox": 
  "Visual Studio Code": "
  "vivaldi-stable": 󰖟
  "google-chrome": 
  "chromium-browser": 
  "LibreOffice": 
  "Geneious Prime": 󰚄
  "Firefox": 
  "- NVIM": 
  "Alacritty": 
  "- Wezterm": 
  "org.wezfurlong.wezterm": 
  "MultiViewer for F1": 
